### ISSUE TITLE
Download Problem on Windows - Hanging Download

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/dcp-preview#11] opened 2018-04-02 15:45 UTC
## Description
This happened 3 times during downloading the `Census of Immune Cells` dataset. There are no error messages for this issue since the stdout on the terminal looks normal:
```
INFO:hca:File MantonBM5_HiSeq_1_XXX.fastq.gz: Retrieving...
INFO:hca:File MantonBM5_HiSeq_1_XXX.fastq.gz: GET SUCCEEDED. Writing to disk.
```
However, the size of the destination folder was not growing. If you check the network activities through Win10's Task Manager, normally you will see 50Mbps-150Mbps(depends on your ISP and service package), but after running into this error, you will see only ~100kbps for hours which means the script/cli is not downloading any data and hanging for hours. 

This error can be resolved by pressing `ctrl` + `c`, which will make the script resume and retry downloading the current `fastq.gz` file. But the root cause of this error and the reason why `ctrl` + `c` can solve the problem are ambiguous to me.

## Environment
- System: Win10 WSL - Ubuntu 16.04
- Python: Python 3.6.0 |Anaconda custom (64-bit)
- Location: Boston, MA
- Script: `time ./hca-download-census.sh`

**Comment by ttung** [comment] 2018-04-02 16:13
I'm 90% sure I know what the problem is, and I have a fix in the works.

**Comment by kislyuk** [comment] 2018-04-03 14:37
This looks like a timeout configuration problem. I believe it's fixed in the latest CLI release, which sets the timeout policy on the requests. Please try and reopen this if the issue persists.

**Closed by kislyuk** 2018-04-03 14:37 UTC
